export const Permission = {
  DASHBOARD_EXECUTIVE_VIEW: "DASHBOARD_EXECUTIVE_VIEW",
  DASHBOARD_OPERATIONAL_VIEW: "DASHBOARD_OPERATIONAL_VIEW",
  SALES_VIEW: "SALES_VIEW",
  CASHIER_VIEW: "CASHIER_VIEW",
  FINANCE_VIEW: "FINANCE_VIEW",
  FINANCE_COMPANY_FUNDING: "FINANCE_COMPANY_FUNDING",
  FINANCE_TRANSFER: "FINANCE_TRANSFER",
  FINANCE_EXPENSE: "FINANCE_EXPENSE",
  FINANCE_VOID: "FINANCE_VOID",
  PURCHASE_VIEW: "PURCHASE_VIEW",
  PURCHASE_CREATE: "PURCHASE_CREATE",
  PURCHASE_APPROVE: "PURCHASE_APPROVE",
  PURCHASE_SPEND_RECORD: "PURCHASE_SPEND_RECORD",
  PURCHASE_RECEIPT_UPLOAD: "PURCHASE_RECEIPT_UPLOAD",
  INVENTORY_VIEW: "INVENTORY_VIEW",
  INVENTORY_INPUT: "INVENTORY_INPUT",
  STOCK_REVIEW: "STOCK_REVIEW",
  REPORT_VIEW: "REPORT_VIEW",
  REPORT_RESEND: "REPORT_RESEND",
  DATA_ISSUE_VIEW: "DATA_ISSUE_VIEW",
  CORRECTION_CREATE: "CORRECTION_CREATE",
  AUDIT_VIEW: "AUDIT_VIEW",
  AUDIT_VIEW_LIMITED: "AUDIT_VIEW_LIMITED",
  SETTINGS_MANAGE: "SETTINGS_MANAGE",
  USER_MANAGE: "USER_MANAGE",
  MENU_MANAGE: "MENU_MANAGE",
  EXPORT_DATA: "EXPORT_DATA",
} as const;

export type PermissionCode = (typeof Permission)[keyof typeof Permission];
export type RoleCode = "OWNER" | "DIRECTOR" | "MANAGER" | "CASHIER" | "KITCHEN";

export const ROLE_SCOPES: Record<RoleCode, ReadonlyArray<string>> = {
  OWNER: ["ALL"],
  DIRECTOR: ["ALL"],
  MANAGER: ["OPERATIONS", "SALES_ALL", "CASHIER_ALL", "INVENTORY_ALL"],
  CASHIER: ["CASHIER_OWN", "BEVERAGE", "INVENTORY_BAR"],
  KITCHEN: ["FOOD", "INVENTORY_KITCHEN"],
};
