"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { useOnlineState } from "@/components/pwa/network-status";

type Props={id:string;status:string;requestDate:string;canCreate:boolean;canApprove:boolean;canSpend:boolean;canReceipt:boolean};
export function PurchaseActions(p:Props){
 const online=useOnlineState(); const router=useRouter(); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 async function call(path:string,body?:unknown){ if(!online)return; setBusy(true);setError("");try{const r=await fetch(`/api/purchase/requests/${p.id}${path}`,{method:"POST",headers:{"content-type":"application/json"},body:body===undefined?undefined:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j?.error?.message??"Aksi gagal");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Aksi gagal")}finally{setBusy(false)}}
 return <div className="panel form-stack"><h2>Actions</h2>
  {(p.status==="DRAFT"||p.status==="REVISION_REQUESTED")&&p.canCreate&&<button className="primary-button" disabled={!online||busy} onClick={()=>call("/submit")}>Submit untuk Approval</button>}
  {p.status==="SUBMITTED"&&p.canApprove&&<Approval onCall={call} disabled={!online||busy}/>} 
  {p.status==="APPROVED"&&p.canApprove&&<div className="inline-form"><select id="fund"><option value="HOUSEBANK">Housebank</option><option value="CASHIER_CASH">Cashier Cash</option></select><button className="primary-button" disabled={!online||busy} onClick={()=>call("/funding-source",{fundAccountCode:(document.getElementById("fund") as HTMLSelectElement).value})}>Tetapkan Sumber Dana</button></div>}
  {p.status==="FUNDED_READY_TO_SPEND"&&p.canSpend&&<Spend date={p.requestDate} onCall={call} disabled={!online||busy}/>} 
  {(p.status==="PURCHASED"||p.status==="RECEIPT_RECORDED")&&p.canReceipt&&<Receipt onCall={call} disabled={!online||busy}/>} 
  {(p.status==="PURCHASED"||p.status==="RECEIPT_RECORDED")&&p.canSpend&&<button className="secondary-button" disabled={!online||busy} onClick={()=>call("/close")}>Close Purchase Request</button>}
  {error&&<p className="error-text">{error}</p>}{!online&&<p className="muted">Approval dan transaksi tidak dapat dikirim saat offline.</p>}
 </div>
}
function Approval({onCall,disabled}:{onCall:(p:string,b?:unknown)=>Promise<void>;disabled:boolean}){const [reason,setReason]=useState("");const [fund,setFund]=useState("HOUSEBANK");return <div className="form-stack"><label>Sumber dana saat approve<select value={fund} onChange={e=>setFund(e.target.value)}><option value="HOUSEBANK">Housebank</option><option value="CASHIER_CASH">Cashier Cash</option><option value="">Tentukan nanti</option></select></label><div className="inline-form"><button className="primary-button" disabled={disabled} onClick={()=>onCall("/decision",{action:"APPROVE",fundAccountCode:fund||undefined})}>Approve</button></div><label>Alasan untuk Revision/Reject<textarea value={reason} onChange={e=>setReason(e.target.value)} /></label><div className="inline-form"><button className="secondary-button" disabled={disabled||!reason.trim()} onClick={()=>onCall("/decision",{action:"REVISE",reason})}>Request Revision</button><button className="danger-button" disabled={disabled||!reason.trim()} onClick={()=>onCall("/decision",{action:"REJECT",reason})}>Reject</button></div></div>}
function Spend({date,onCall,disabled}:{date:string;onCall:(p:string,b?:unknown)=>Promise<void>;disabled:boolean}){const [amount,setAmount]=useState("");const [desc,setDesc]=useState("");const [vendor,setVendor]=useState("");const [businessDate,setDate]=useState(date);return <div className="form-stack"><h3>Catat Actual Spend</h3><label>Business Date<input type="date" value={businessDate} onChange={e=>setDate(e.target.value)}/></label><label>Amount<input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="numeric"/></label><label>Description<input value={desc} onChange={e=>setDesc(e.target.value)}/></label><label>Staff/Vendor<input value={vendor} onChange={e=>setVendor(e.target.value)}/></label><button className="primary-button" disabled={disabled||!amount||!desc} onClick={()=>onCall("/spend",{businessDate,amount,expenseCategoryCode:"UNMAPPED",description:desc,counterpartyName:vendor||undefined})}>Post Expense</button><p className="muted">Kategori expense default UNMAPPED sampai master kategori cafe dilengkapi.</p></div>}
function Receipt({onCall,disabled}:{onCall:(p:string,b?:unknown)=>Promise<void>;disabled:boolean}){const [url,setUrl]=useState("");const [fileId,setFileId]=useState("");return <div className="form-stack"><h3>Receipt / Nota</h3><label>Google Drive / file URL<input type="url" value={url} onChange={e=>setUrl(e.target.value)}/></label><label>Storage File ID<input value={fileId} onChange={e=>setFileId(e.target.value)}/></label><button className="primary-button" disabled={disabled||!url||!fileId} onClick={()=>onCall("/receipt",{storageProvider:"GOOGLE_DRIVE",storageFileId:fileId,fileUrl:url})}>Simpan Receipt</button></div>}
